(function() {
    olark.extend('Sounds');

    var isNewVersion = olark._ && olark._.versions && (olark._.versions.follow || olark._.versions.popout)
    if (isNewVersion) {
        olark._.finish({
            "system": {
                "hide_when_away": 0,
                "rtl": false,
                "send_transcript_complete_button_text": "Transcript Sent",
                "hb_primary_color": "#F04405",
                "show_away_as_header": 0,
                "send_transcript_placeholder": "Email",
                "offline_survey_website_placeholder": "Enter your website...",
                "close_hides_window": false,
                "feedback_survey_button_submitting": "Submitting",
                "disable_offline_messaging_fallback": true,
                "disable_get_cookies": false,
                "restart_chat_online_button_text": "Start conversation",
                "corner_position": "BR",
                "right_margin": 10,
                "operator_is_typing_text": "is typing...",
                "sending_text": "sending",
                "hb_dark_theme": false,
                "feedback_survey_complete_button_text": "Feedback Sent",
                "offline_survey_next_button_text": "Next",
                "dismiss_message_text": "Dismiss",
                "default_flash_off_icon": "https://static.olark.com/js/images/white.ico",
                "offline_survey_email_label": "Email",
                "feedback_survey_question_operator_intelligence_text": "How knowledgeable was the chat agent?",
                "feedback_survey_question_operator_speed_low": "Not at all responsive",
                "show_end_popout": 0,
                "hb_show_as_tab": false,
                "allowed_domains": "",
                "offline_header_text": "Contact us!",
                "prechat_email_validation_message": "Please enter a valid email address",
                "local_user_display_name": "\u0026rarr;",
                "habla_offline_submit_value": "Send",
                "offline_survey_submit_button_text": "Send",
                "conversation_id_error_text": "File uploading is currently unavailable.",
                "habla_closebutton_text": "x",
                "prechat_survey_welcome_message": "Hi! Let\u2019s get some quick info so we can better serve you:",
                "prechat_survey_name_label": "Name",
                "disable_set_cookies": false,
                "url_handler_target_window": "_top",
                "resize_input_height": 60,
                "not_available_text": "Contact us!",
                "poll": false,
                "branding": "powered_by",
                "prechat_survey_email_placeholder": "Enter your email...",
                "disable_expand_text_input": false,
                "habla_special_div_show_type": "block",
                "feedback_survey_question_chat_low": "Not at all satisfied",
                "prechat_survey_email_label": "Email",
                "hb_disable_mobile": false,
                "resize_length": 25,
                "feedback_survey_submission_error_message": "There was an error submitting your answer, please try again.",
                "enable_google_analytics": false,
                "offline_survey_phone_placeholder": "Enter your phone number...",
                "feedback_survey_button_finish": "Finish",
                "hb_chatbox_size": "md",
                "google_analytics_domain": "auto",
                "offline_message": "We're not around, but we'd love to chat another time.",
                "feedback_survey_question_chat_high": "Extremely satisfied",
                "offline_survey": {
                    "pages": [
                        [{
                            "is_required": true,
                            "type": "name"
                        }, {
                            "is_required": true,
                            "type": "email"
                        }, {
                            "placeholder_text": "",
                            "is_required": true,
                            "type": "textarea",
                            "label": "Message"
                        }]
                    ]
                },
                "feedback_survey_question_operator_intelligence_high": "Extremely knowledgeable",
                "file_size_error_text": "This file size is too large.",
                "visitor_id_error_text": "File uploading is currently unavailable.",
                "bottom_margin": 10,
                "offline_survey_thank_you_message": "Thanks! We will have a member of our team contact you shortly.",
                "url_handler": "https://static.olark.com/jsclient-latest/follow.html?v=1426711435610",
                "right_to_left": false,
                "default_flash_on_icon": "https://static.olark.com/js/images/orange.ico",
                "busy_message": "All of our representatives are with other customers at this time. We will be with you shortly.",
                "divid": "habla_window_div",
                "feedback_survey_question_3_text": "Question 3 of 5",
                "hide_min_max_buttons": 0,
                "online_header_text": "Now chatting",
                "offline_phone_validation_message": "Please enter a valid phone number",
                "end_chat_button_text": "End Chat",
                "hb_show_button_text": false,
                "prechat_survey_submit_button_text": "Start chatting",
                "offline_required_error_message": "Please complete all required fields",
                "feedback_survey_question_5_text": "Question 5 of 5",
                "feedback_survey_button_next": "Next",
                "generic_upload_error_text": "File uploading is currently unavailable.",
                "prechat_survey": {
                    "is_enabled": false,
                    "pages": [
                        [{
                            "is_required": false,
                            "type": "email"
                        }]
                    ]
                },
                "email_body_error_text": "You must complete all fields and specify a valid email address",
                "habla_offline_email_text": "click here and type your Email",
                "feedback_survey_cancel_text": "Cancel",
                "feedback_survey_question_additional_feedback_placeholder": "Type message here",
                "prechat_required_error_message": "Please complete all required fields",
                "append_to_body": 1,
                "habla_sizebutton_text_compressed": "^",
                "line_length": 21,
                "feedback_survey_question_2_text": "Question 2 of 5",
                "feedback_survey_question_operator_speed_text": "How responsive was the chat agent?",
                "offline_email_validation_message": "Please enter a valid email address",
                "habla_offline_phone_text": "click here and type your Phone Number",
                "pre_chat_submit": "Click here to start chatting",
                "check_for_status": "Olark Chat (startup)",
                "offline_msg_mode": 1,
                "require_offline_phone": 0,
                "top_margin": 10,
                "say_text": "Type here and hit enter to chat",
                "offline_survey_email_placeholder": "Enter your email...",
                "hide_not_available": 0,
                "file_type_error_text": "This file type is not allowed.",
                "prechat_survey_phone_placeholder": "Enter your phone number...",
                "expandOnMessageReceived": 0,
                "branding_link_text": "Powered by Olark",
                "branding_panel_message_text": "10,000+ companies rely on Olark software to chat with customers directly.",
                "feedback_survey_question_operator_attitude_high": "Extremely friendly",
                "pre_chat_error_text": "Please enter your name and email in case we get disconnected.",
                "left_margin": 10,
                "disable_default_visitor_information": 0,
                "prechat_survey_next_button_text": "Next",
                "require_name": 2,
                "use_theme": "cryptic_capybara",
                "parse_links": 1,
                "feedback_survey_question_additional_feedback_text": "Additional Feedback.",
                "before_chat_text": "Chat with us",
                "disableGoogleAnalytics": 0,
                "habla_popout_text": "\u0026gt;",
                "restart_chat_offline_button_text": "Leave a message",
                "is_inline": 0,
                "language": "en",
                "width": 260,
                "flash_titlebar": 1,
                "show_popout": 0,
                "feedback_survey_question_operator_attitude_text": "How friendly was the chat agent?",
                "hb_position": "right",
                "require_phone": 0,
                "myname": "you",
                "ended_chat_message": "This chat has ended.",
                "feedback_survey_question_operator_speed_high": "Extremely responsive",
                "offline_button_text": "Contact us",
                "offline_survey_name_placeholder": "Enter your name...",
                "height": 155,
                "default_localization": "en-US",
                "busy_text": "Contact us",
                "start_habla_window_visible": false,
                "habla_offline_body_text": "We're not around but we still want to hear from you! Leave us a note:",
                "branding_panel_link_text": "Try Olark on your site",
                "is_popup": 0,
                "hashchange_events_trigger_page_change": 1,
                "feedback_survey_end_message": "Thank you for your feedback :)",
                "expandOnFirstMessageReceived": 1,
                "enable_buttons": 1,
                "habla_offline_sent_text": "Thanks for your message! We'll get back to you shortly.",
                "upload_rejected_error_text": "File uploading is currently unavailable.",
                "cookie_path": "/",
                "offline_survey_welcome_message": "No agent online to chat. Fill out the form and we will get back to you!",
                "feedback_survey_question_1_text": "Question 1 of 5",
                "offline_survey_website_label": "Website",
                "processing_file_error_text": "There was a problem processing your file.",
                "feedback_survey_question_operator_intelligence_low": "Not at all knowledgeable",
                "show_away": 0,
                "send_text": "Send",
                "operator_has_stopped_typing_text": "has stopped typing",
                "offline_survey_name_label": "Name",
                "prechat_phone_validation_message": "Please enter a valid phone number",
                "start_visible": false,
                "in_chat_text": "Now chatting",
                "habla_name_input_text": "click here and type your Name",
                "panel_offset": 20,
                "hbl_cookie_path": "/",
                "send_transcript_title_text": "Send Transcript",
                "input_height": 20,
                "habla_sizebutton_text_expanded": "_",
                "prechat_survey_website_placeholder": "Enter your website...",
                "feedback_survey_question_operator_attitude_low": "Not at all friendly",
                "enableLanguageTranslation": false,
                "flash_icons": 1,
                "hb_custom_style": {
                    "general": {
                        "secondaryColor": null,
                        "corners": "soft"
                    }
                },
                "require_email": 1,
                "prechat_survey_website_label": "Website",
                "hb_theme_override": {
                    "bg_image_size": "130px",
                    "primary_color": "#751A33",
                    "enabled": false,
                    "bg_image_url": "https://static.olark.com/a/theme/images/seasonal-fall-1.png",
                    "expiration_date": "1678895286"
                },
                "show_pre_chat": 0,
                "pre_chat_message": "Questions? We'd love to chat.",
                "branding_panel_cancel_text": "Go back",
                "offline_survey_phone_label": "Phone",
                "send_transcript_begin_button_text": "Send Transcript",
                "habla_end_popout_text": "",
                "feedback_survey_question_chat_text": "How satisfied were you with this chat?",
                "prechat_website_validation_message": "Please enter a valid URL",
                "send_transcript_cancel_text": "No Thanks",
                "send_transcript_error_text": "Please enter a valid email address",
                "start_expanded": 0,
                "prechat_survey_name_placeholder": "Enter your name...",
                "away_text": "Contact us",
                "prechat_survey_phone_label": "Phone",
                "online_button_text": "Chat with us",
                "feedback_survey_question_4_text": "Question 4 of 5",
                "start_hidden": 0,
                "hb_enable_uploads": true,
                "offline_website_validation_message": "Please enter a valid URL",
                "feedback_survey_begin_button_text": "Rate Chat",
                "welcome_msg": "Questions?",
                "plugin_path": "https://static.olark.com/js/plugins/",
                "show_in_buddy_list": "all",
                "hkey": "PHNwYW4gc3R5bGU9ImRpc3BsYXk6bm9uZSI+PGEgaWQ9ImhibGluazkiPjwvYT5odHRwOi8vd3d3Lm9sYXJrLmNvbTwvc3Bhbj5Qb3dlcmVkIEJ5IDxhIGhyZWY9Imh0dHA6Ly93d3cub2xhcmsuY29tLz9yaWQ9OTE4NS05MTktMTAtODcwNyZhbXA7cG93ZXJlZF9mPTEmYW1wO3V0bV9tZWRpdW09d2lkZ2V0JmFtcDt1dG1fY2FtcGFpZ249cG93ZXJlZF9ieV9mcmVlJmFtcDt1dG1fc291cmNlPTkxODUtOTE5LTEwLTg3MDciIGlkPSJoYmxpbms5OSIgdGFyZ2V0PSJfYmxhbmsiPk9sYXJrPC9hPg==",
                "md5": "4f270dd34c48063eb40433583594049e",
                "site_id": "9185-919-10-8707",
                "template": null,
                "operators": {}
            },
            "Sounds": {
                "enabled": true
            }
        });
    } else {
        olark.configure(function(conf) {
            conf.system.site_id = "9185-919-10-8707";
        });
        olark._.finish();
    }
})();